"""Cognify task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTbgRl_mL7NE7HV_95vV0Va3bfiJpDdS
"""
#cognify level 2(task 3)
# Task: Feature Engineering

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# Load the dataset
df = pd.read_csv('Dataset .csv')


# Extract additional features from the existing columns, such as the length of the restaurant name or address.
# 🔹 Create a new feature: Length of restaurant name
df['Restaurant Name Length'] = df['Restaurant Name'].astype(str).apply(len)

# 🔹 Create another feature: Length of address (if present)
df['Address Length'] = df['Address'].astype(str).apply(len)

# Display the new features
print("🔹 Sample of New Features:\n")
print(df[['Restaurant Name', 'Restaurant Name Length', 'Address', 'Address Length']].head())


#Create new features like "Has Table Booking" or "Has Online Delivery" by encoding categorical variables.

# 🔹 Encode 'Has Table booking': Yes → 1, No → 0
df['Has Table Booking (Binary)'] = df['Has Table booking'].apply(lambda x: 1 if x == 'Yes' else 0)

# 🔹 Encode 'Is delivering now': Yes → 1, No → 0
df['Has Online Delivery (Binary)'] = df['Is delivering now'].apply(lambda x: 1 if x == 'Yes' else 0)

# 🔸 Show the new columns
print("🔹 Encoded Features Sample:\n")
print(df[['Has Table booking', 'Has Table Booking (Binary)', 'Is delivering now', 'Has Online Delivery (Binary)']].head())

