"""Cognify task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTbgRl_mL7NE7HV_95vV0Va3bfiJpDdS
"""
#cognify level 2(task 1)
# Task: Table Booking and Online Delivery

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import plotly.express as px
# Load the dataset
df = pd.read_csv('Dataset .csv')

#Determine the percentage of restaurants that offer table booking and online delivery.
# 🔹 Percentage of restaurants offering table booking
table_booking_counts = df['Has Table booking'].value_counts()
table_booking_percent = (table_booking_counts / len(df)) * 100

print("🔹 Table Booking Availability (in %):\n")
print(table_booking_percent)

# 🔹 Percentage of restaurants offering online delivery
online_delivery_counts = df['Is delivering now'].value_counts()
online_delivery_percent = (online_delivery_counts / len(df)) * 100

print("\n🔹 Online Delivery Availability (in %):\n")
print(online_delivery_percent)


#Compare the average ratings of restaurants with table booking and those without
# Step 1: Convert 'Aggregate rating' to numeric
df['Aggregate rating'] = pd.to_numeric(df['Aggregate rating'], errors='coerce')

# Step 2: Group by 'Has Table booking' and calculate average rating
avg_ratings = df.groupby('Has Table booking')['Aggregate rating'].mean()

# Step 3: Display results
print("🔹 Average Rating (With vs Without Table Booking):\n")
print(avg_ratings)


# Analyze the availability of online delivery among restaurants with different price ranges.
# Step 1: Check columns
# Ensure 'Price range' is numeric and 'Is delivering now' is consistent
df['Price range'] = pd.to_numeric(df['Price range'], errors='coerce')

# Step 2: Group by 'Price range' and 'Is delivering now'
delivery_by_price = df.groupby(['Price range', 'Is delivering now']).size().unstack().fillna(0)

# Step 3: Display results
print("🔹 Online Delivery Availability by Price Range:\n")
print(delivery_by_price)

# Step 4: Plot it
delivery_by_price.plot(kind='bar', stacked=True, figsize=(8,5), colormap='Set2')
plt.title('Online Delivery vs Price Range')
plt.xlabel('Price Range')
plt.ylabel('Number of Restaurants')
plt.xticks(rotation=0)
plt.legend(title='Online Delivery')
plt.tight_layout()
plt.show()
