"""Cognify task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTbgRl_mL7NE7HV_95vV0Va3bfiJpDdS
"""
#cognify level 1(task 2)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Load the dataset
df = pd.read_csv('Dataset .csv')
#Calculate basic statistical measures (mean,median, standard deviation, etc.) for numerical columns
# Convert necessary columns to numeric (in case they are object types)
df['Aggregate rating'] = pd.to_numeric(df['Aggregate rating'], errors='coerce')
df['Votes'] = pd.to_numeric(df['Votes'], errors='coerce')
df['Price range'] = pd.to_numeric(df['Price range'], errors='coerce')

# Get basic statistical summary
print("🔹 Basic Statistical Measures for Numerical Columns:\n")
print(df.describe())

# Get median separately (since it's not included in .describe())
print("\n🔹 Median Values:\n")
print(df.median(numeric_only=True))

# Explore the distribution of categorical variables like "Country Code," "City," and "Cuisines".
# 🔹 View top 10 most frequent Country Codes
print("🔹 Top 10 Country Codes:\n")
print(df['Country Code'].value_counts().head(10))

# 🔹 View top 10 most common Cities
print("\n🔹 Top 10 Cities:\n")
print(df['City'].value_counts().head(10))

# 🔹 View top 10 most common Cuisines
print("\n🔹 Top 10 Cuisines:\n")
print(df['Cuisines'].value_counts().head(10))

# Optional: Plot the top 10 cities
plt.figure(figsize=(10,5))
sns.countplot(y='City', data=df, order=df['City'].value_counts().head(10).index, palette='magma')
plt.title('Top 10 Cities with Most Restaurants')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.tight_layout()
plt.show()

# Identify the top cuisines and cities with the highest number of restaurants
# 🔹 Top 10 cities with the highest number of restaurants
print("🔹 Top 10 Cities with Most Restaurants:\n")
top_cities = df['City'].value_counts().head(10)
print(top_cities)

# 🔹 Top 10 cuisines served by most restaurants
print("\n🔹 Top 10 Cuisines by Restaurant Count:\n")
top_cuisines = df['Cuisines'].value_counts().head(10)
print(top_cuisines)

# 🔸 Optional: Plot Top Cities
plt.figure(figsize=(10, 5))
sns.barplot(x=top_cities.values, y=top_cities.index, palette='plasma')
plt.title('Top 10 Cities with Most Restaurants')
plt.xlabel('Number of Restaurants')
plt.ylabel('City')
plt.tight_layout()
plt.show()

# 🔸 Optional: Plot Top Cuisines
plt.figure(figsize=(10, 5))
sns.barplot(x=top_cuisines.values, y=top_cuisines.index, palette='coolwarm')
plt.title('Top 10 Most Popular Cuisines')
plt.xlabel('Number of Restaurants')
plt.ylabel('Cuisine')
plt.tight_layout()
plt.show()
