"""Cognify task

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XTbgRl_mL7NE7HV_95vV0Va3bfiJpDdS
"""
#cognify level 1(task 1)

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

#identify the number of rows and columns
# Load dataset
df = pd.read_csv('Dataset .csv')

rows, columns = df.shape
print("Number of rows:", rows)
print("Number of columns:", columns)

# Check for missing values in each column and handle them accordingly.
missing_values = df.isnull().sum()
print("Missing values in each column:")
print(missing_values[missing_values > 0])
print("\nMissing values after handling:")
print(df.isnull().sum())

#Perform data type conversion if necessary.Analyze the distribution of the target variable ("Aggregate rating") and identify any class imbalances
# Step 1: Convert 'Aggregate rating' to numeric if needed
df['Aggregate rating'] = pd.to_numeric(df['Aggregate rating'], errors='coerce')

# Step 2: Check data type after conversion
print(" Data Type After Conversion:\n")
print(df['Aggregate rating'].dtypes)

# Step 3: Check unique values and their counts
print("\n Distribution of 'Aggregate rating':\n")
rating_counts = df['Aggregate rating'].value_counts().sort_index()
print(rating_counts)

# Step 4: Visualize the distribution
plt.figure(figsize=(8,4))
sns.countplot(x='Aggregate rating', data=df, palette='Blues', order=sorted(df['Aggregate rating'].dropna().unique()))
plt.title("Distribution of Aggregate Ratings")
plt.xlabel("Aggregate Rating")
plt.ylabel("Number of Restaurants")
plt.tight_layout()
plt.show()
